package chata.can.chata_ai.request.poll

import chata.can.chata_ai.pojo.request.RequestBuilder.callStringRequest
import chata.can.chata_ai.pojo.request.StatusResponse
import com.android.volley.Request

object Poll
{
	fun callPoll(listener: StatusResponse)
	{
		val url = "https://spira-staging.chata.io/autoql/api/v1/" +
			"rules/notifications/summary/poll?key=" +
			"AIzaSyD4ewBvQdgdYfXl3yIzXbVaSyWGOcRFVeU" +
			"&unacknowledged=0"
		val mAuthorization = hashMapOf("Authorization" to "Bearer eyJ0eXAiOiAiSldUIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiNzUxZmYzY2YxMjA2ZGUwODJhNzM1MjY5OTI2ZDg0NTgzYjcyOTZmNCJ9.eyJpYXQiOiAxNjAwODE1ODMzLCAiZXhwIjogMTYwMDgzNzQzMywgImlzcyI6ICJkZW1vMy1qd3RhY2NvdW50QHN0YWdpbmctMjQ1NTE0LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwgImF1ZCI6ICJkZW1vMy1zdGFnaW5nLmNoYXRhLmlvIiwgInN1YiI6ICJkZW1vMy1qd3RhY2NvdW50QHN0YWdpbmctMjQ1NTE0LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwgImVtYWlsIjogImRlbW8zLWp3dGFjY291bnRAc3RhZ2luZy0yNDU1MTQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCAicHJvamVjdF9pZCI6ICJzcGlyYS1kZW1vMyIsICJ1c2VyX2lkIjogImNhcmxvc0ByaW5yby5jb20ubXgiLCAiZGlzcGxheV9uYW1lIjogImNhcmxvc0ByaW5yby5jb20ubXgiLCAicmVzb3VyY2VfYWNjZXNzIjogWyIvYXV0b3FsL2FwaS92MS9xdWVyeS8qKiIsICIvYXV0b3FsL2FwaS92MS9ub3RpZmljYXRpb25zLyoqIiwgIi9hdXRvcWwvYXBpL3YxL3J1bGVzLyoqIiwgIi9hdXRvcWwvYXBpL3YxL3J1bGVzIiwgIi9hdXRvcWwvYXBpL3YxL3F1ZXJ5Il19.LtSRGlLxFE0KHZ7vQsla9C9lZ4F-KrNwn5byg-d1rGrPU7eWxAqIVxWtDqKbjyMKUFk3sY_O5_1nAqF5knYgJXpq1s3KqcvuTfm3dk3aSuShy3NfSE9gSqN5bE6xHf0xqLfvS9mweybaoA6KmS1A6GCner9Hd4xvWt6dOm8oJ2acZVArhlVG2fKASvMkAwshwXHLGdWU-ZPuqYLIPy-vE2sQwxxVsdkSUUG0WnSMQG2rewdNcX9Itye7_slSXE8N2e9BJuQdRq4xxItNWlFJ6PlPXXBxYZccymDAP8fRIu2x2oBYQNuFVaHi4qCsmQ2yaLZbOD5XTXBn77AMCGbXOw==")
		callStringRequest(
			Request.Method.GET,
			url,
			headers = mAuthorization,
			listener = listener)
	}
}